version: "3.9"
services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile.back
    network_mode: host
    volumes:
    - ./backend:/backend

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile.front
    network_mode: host
    volumes:
    - ./frontend:/frontend