[[rooms]]
RoomName = "Ruby Room"
Image = "rubyroom.png"

[[rooms.RoomObjects]]
ObjectName =  "CeilingLights"
StateType = "Toggle"
ControlLocation = [10, 0]
ControlOrientation = 0
TrueTxt = "Turn Off Ceiling Lights"
FalseTxt = "Turn On Ceiling Lights"

[[rooms.RoomObjects]]
ObjectName =  "Door"
StateType = "Toggle"
ControlLocation = [0, 0]
ControlOrientation = 0
TrueTxt = "Close Door"
FalseTxt = "Open Door"

[[rooms.RoomObjects]]
ObjectName =  "Blinds"
StateType = "Toggle"
ControlLocation = [0, 20]
ControlOrientation = 0
TrueTxt = "Close Blinds"
FalseTxt = "Open Blinds"

[[rooms.RoomObjects]]
ObjectName =  "WallLights"
StateType = "Toggle"
ControlLocation = [10, 20]
ControlOrientation = 0
TrueTxt = "Turn Off Wall Lights"
FalseTxt = "Turn On Wall Lights"

[[rooms]]
RoomName = "Diamond Room"
Image = "diamondroom.png"

[[rooms.RoomObjects]]
ObjectName =  "CeilingLights"
StateType = "Toggle"
ControlLocation = [5, 25]
ControlOrientation = 0
TrueTxt = "Turn Off Ceiling Lights"
FalseTxt = "Turn On Ceiling Lights"

[[rooms.RoomObjects]]
ObjectName =  "Door"
StateType = "Toggle"
ControlLocation = [15, 5]
ControlOrientation = 0
TrueTxt = "Close Door"
FalseTxt = "Open Door"

[[rooms.RoomObjects]]
ObjectName =  "Blinds"
StateType = "Toggle"
ControlLocation = [15, 25]
ControlOrientation = 0
TrueTxt = "Close Blinds"
FalseTxt = "Open Blinds"

[[rooms.RoomObjects]]
ObjectName =  "WallLights"
StateType = "Toggle"
ControlLocation = [5, 5]
ControlOrientation = 0
TrueTxt = "Turn Off Wall Lights"
FalseTxt = "Turn On Wall Lights"

[[rooms.RoomObjects]]
ObjectName =  "AdjustableWallLights"
StateType = "Percentage"
ControlLocation = [20, 20]
SliderText = "Change Light Level"