[Corridor]
Image = "rubyroom.png"

[Corridor.RoomObjects.wall]
StateType = "Toggle"
ControlLocation = [45, 40]
ControlOrientation = 0
TrueTxt = "Turn Off Wall Lights"
FalseTxt = "Turn On Wall Lights"

[Corridor.RoomObjects.ceiling]
StateType = "Toggle"
ControlLocation = [87, 51]
ControlOrientation = 0
TrueTxt = "Turn Off Ceiling Lights"
FalseTxt = "Turn On Ceiling Lights"



[Labextension]
Image = "diamondroom.png"

[Labextension.RoomObjects.table]
StateType = "Toggle"
ControlLocation = [40, 20]
ControlOrientation = 0
TrueTxt = "Turn Off Table Lights"
FalseTxt = "Turn On Table Lights"



[Door1]
Image = "rubyroom.png"

[Door1.RoomObjects.ceiling]
StateType = "Toggle"
ControlLocation = [60, 50]
ControlOrientation = 0
TrueTxt = "Turn Off Ceiling Lights"
FalseTxt = "Turn On Ceiling Lights"



[Door2]
Image = "diamondroom.png"

[Door2.RoomObjects.ceiling]
StateType = "Toggle"
ControlLocation = [60, 45]
ControlOrientation = 0
TrueTxt = "Turn Off Ceiling Lights"
FalseTxt = "Turn On Ceiling Lights"

[Door2.RoomObjects.blinds]
StateType = "Percentage"
ControlLocation = [95, 70]
SliderText = "Open Blinds"